#@data/values

---
replicaCount: 2
env:
 #@overlay/append
  - name: SPRING_PROFILES_ACTIVE
    value: mysql,wavefront
 #@overlay/append
  - name: MYSQL_USER
    value: petclinic
 #@overlay/append
  - name: MYSQL_PASS
    value: petclinic
 #@overlay/append
  - name: MYSQL_URL
    value: jdbc:mysql://petclinic-mysql.default.svc.cluster.local:3306/petclinic
image:
  image: dev.registry.pivotal.io/warroyo/petclinic:latest
  imagePullSecrets:
  #@overlay/append
  - name: devregistry
  pullPolicy: IfNotPresent