#@ load("@ytt:data", "data")

apiVersion: v1
kind: Service
metadata:
  name:  #@ data.values.service.name
  labels:
    app: #@ data.values.service.name
spec:
  type: #@ data.values.service.type
  ports:
    - port: #@ data.values.service.port
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: #@ data.values.name
