apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: petclinic
  labels:
    chart: {{ template "petclinic.chart" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"