apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: petclinic-virtual-service
  labels:
    chart: {{ template "petclinic.chart" . }}
    release: {{ .Release.Name }}
spec:
  hosts:
  - petclinic.lab.home
  - {{ .Values.service.name }}.{{ .Release.Namespace }}.svc.cluster.local
  gateways:
  - petclinic
  http:
  - match:
    - headers:
        api-version:
          exact: {{.Values.productionDeployment.apiversion}}
    route:
    - destination:
        host: {{ .Values.service.name }}.{{ .Release.Namespace }}.svc.cluster.local
        subset: {{.Values.productionDeployment.apiversion}}
        port:
          number: {{ .Values.service.port }}    
  - match:
    - headers:
        api-version:
          exact: {{.Values.canaryDeployment.apiversion}}
    route:
    - destination:
        host: {{ .Values.service.name }}.{{ .Release.Namespace }}.svc.cluster.local
        subset: {{.Values.canaryDeployment.apiversion}}
        port:
          number: {{ .Values.service.port }}    
  - route:
    - destination:
        host: {{ .Values.service.name }}.{{ .Release.Namespace }}.svc.cluster.local
        subset: production
        port:
          number: {{ .Values.service.port }}
      weight: {{ .Values.productionDeployment.weight }}
    - destination:
        host: {{ .Values.service.name }}.{{ .Release.Namespace }}.svc.cluster.local
        subset: canary
        port:
          number: {{ .Values.service.port }}
      weight: {{ .Values.canaryDeployment.weight }}